### ISSUE TITLE
Advice for noob

### ISSUE THREAD

**Issue by jenarehorka** [Marc56K/ElectricityMeterCam#1]
Hey, I like this project. I would love to give try. Would you be so kind and help me how to instal this into a esp32cam? Which file is the main one? Should i install it over Arduino IDE or esp flasher tool? What variables should be added before instal? (Wifi credentials etc.) thank you Jan

**Comment by Marc56K** [comment]
Hi Jenarehorka,

sorry for the poor documentation of this project. You need PlatformIO to build and flash the firmware to your esp32cam. The Arduino IDE is currently not supported. Before building, you have to rename the file include/wifi_config.h.default to include/wifi_config.h and edit the file to match your wifi credentials.

If you are looking for a more mature solution, I can also recommend the following project:
Video: https://www.youtube.com/watch?v=iUgxwbfkIqU
Repo: https://github.com/jomjol/AI-on-the-edge-device/

best regards,
Marc
